version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: dummy
    password: dummy-since-this-is-a-public-repo

updates:
  - package-ecosystem: "gradle"
    directory: "/v4"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    reviewers:
      - quotidian-ennui
      - mcwarman
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella
  - package-ecosystem: "gradle"
    directory: "/v3"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    reviewers:
      - quotidian-ennui
      - mcwarman
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella